openapi: '3.0.3'
info:
  version: '1.0.0'
  title: 'FooService'
paths:
  /animal:
    put:
      summary: put parent
      operationId: putParent
      parameters:
        - name: name
          in: path
          required: true
          description: Name of the account being updated.
          schema:
            type: string
      requestBody:
        description: The updated account definition to save.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Zoo'
      responses:
        '200':
          $ref: '#/components/responses/Zoo'
components:
  schemas:
    Zoo:
      type: object
      properties:
        animals:
          type: array
          items:
            $ref: '#/components/schemas/Animal'
    Animal:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          enum: [CAT, DOG]
      discriminator:
        propertyName: type
        mapping:
          CAT: "#/components/schemas/Cat"
          DOG: "#/components/schemas/Dog"
    Cat:
      allOf:
        - $ref: "#/components/schemas/Animal"
        - type: object
          properties:
            purrs:
              type: boolean
    Dog:
      allOf:
        - $ref: "#/components/schemas/Animal"
        - type: object
          properties:
            barks:
              type: boolean
