openapi: '3.0.3'
info:
  version: '1.0.0'
  title: 'FooService'
paths:
  /animal:
    put:
      summary: put parent
      operationId: putParent
      parameters:
        - name: name
          in: path
          required: true
          description: Name of the account being updated.
          schema:
            type: string
      requestBody:
        description: The updated account definition to save.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Zoo'
      responses:
        '200':
          $ref: '#/components/responses/Zoo'
components:
  schemas:
    Zoo:
      type: object
      properties:
        animals:
          type: array
          items:
            $ref: '#/components/schemas/Animal'
    Dog:
      allOf:
        - $ref: '#/components/schemas/Animal'
        - $ref: '#/components/schemas/Dog_allOf'
    Cat:
      allOf:
        - $ref: '#/components/schemas/Animal'
        - $ref: '#/components/schemas/Cat_allOf'
    Animal:
      discriminator:
        propertyName: className
      properties:
        className:
          type: string
        color:
          default: red
          type: string
      required:
        - className
      type: object
    Dog_allOf:
      properties:
        breed:
          type: string
      type: object
    Cat_allOf:
      properties:
        declawed:
          type: boolean
      type: object
