<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
														xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
														xmlns:xsd="http://www.w3.org/2001/XMLSchema"
														xmlns:sws_xsd="http://webservices.sabre.com/sabreXML/2011/10"
														xmlns:sws="https://webservices.sabre.com/websvc"
														xmlns:eb="http://www.ebxml.org/namespaces/messageHeader"
														xmlns:wsse="http://schemas.xmlsoap.org/ws/2002/12/secext"
														targetNamespace="https://webservices.sabre.com/websvc">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://webservices.sabre.com/sabreXML/2011/10" schemaLocation="VoidTicketLLS2.1.0RQRS.xsd"/>
			<xsd:import namespace="http://www.ebxml.org/namespaces/messageHeader" schemaLocation="msg-header-2_0.xsd"/>
			<xsd:import namespace="http://schemas.xmlsoap.org/ws/2002/12/secext" schemaLocation="wsse.xsd"/>
			<xsd:import namespace="http://services.sabre.com/STL/v01" schemaLocation="STL_For_SabreProtocol_v.1.2.0.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="VoidTicketInput">
		<wsdl:part name="header" element="eb:MessageHeader"/>
		<wsdl:part name="header2" element="wsse:Security"/>
		<wsdl:part name="body" element="sws_xsd:VoidTicketRQ"/>
	</wsdl:message>
	<wsdl:message name="VoidTicketOutput">
		<wsdl:part name="header" element="eb:MessageHeader"/>
		<wsdl:part name="header2" element="wsse:Security"/>
		<wsdl:part name="body" element="sws_xsd:VoidTicketRS"/>
	</wsdl:message>
	<wsdl:portType name="VoidTicketPortType">
		<wsdl:operation name="VoidTicketRQ">
			<wsdl:input message="sws:VoidTicketInput"/>
			<wsdl:output message="sws:VoidTicketOutput"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="VoidTicketSoapBinding" type="sws:VoidTicketPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="VoidTicketRQ">
			<soap:operation soapAction="VoidTicketLLSRQ"/>
			<wsdl:input>
				<soap:header message="sws:VoidTicketInput" part="header" use="literal"/>
				<soap:header message="sws:VoidTicketInput" part="header2" use="literal"/>
				<soap:body parts="body" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:header message="sws:VoidTicketOutput" part="header" use="literal"/>
				<soap:header message="sws:VoidTicketOutput" part="header2" use="literal"/>
				<soap:body parts="body" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="VoidTicketService">
		<wsdl:port name="VoidTicketPortType" binding="sws:VoidTicketSoapBinding">
			<soap:address location="https://webservices.havail.sabre.com/websvc"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>